blank_issues_enabled: false
contact_links:
  - name: 💬 Project Discussions
    url: https://github.com/CISCODE-MA/authpackage_swift/discussions
    about: Ask questions or discuss ideas
  - name: 👤 Contact the maintainer
    url: https://github.com/Zaiidmo
    about: Reach out to the maintainer directly
  - name: Email the maintainer
    url: mailto:z.moumni@ciscod.com
    about: Private contact via email
